### ISSUE TITLE
System.IO.FileNotFoundException: Could not load assembly 'System.Buffers

### ISSUE THREAD

**Issue by keshavk** [Krumelur/EFCoreFormsDemo#1]
After adding Microsoft.EntityFrameworkCore.Sqlite nuget package i am getting following error in Android project. iOS is running successfully.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Buffers.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	XFTemplate.Android

**Comment by keshavk** [comment]
I downgraded Sqlite version to 2.1.0 and android project build successfully.
But for iOS i am getting below error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Can't resolve the reference 'System.ReadOnlySpan`1<System.Char> System.MemoryExtensions::AsSpan(System.String,System.Int32,System.Int32)', referenced from the method 'System.ReadOnlySpan`1<System.Char> Microsoft.Extensions.Primitives.StringSegment::AsSpan()' in 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	EFCoreDemo.iOS

**Comment by Goncharuk-Nikita** [comment]
Yes, I also have the same problem, but version 2.1.0 did not help

Can not resolve reference: `System.Memory`, referenced by `Microsoft.Extensions.Primitives`. Please add a NuGet package or assembly reference for `System.Memory`, or remove the reference to `Microsoft.Extensions.Primitives`.	EFCoreDemo.Android

**Comment by NipunKalra** [comment]
@Goncharuk-Nikita you can follow this to solve the problem [https://github.com/xamarin/xamarin-android/issues/2534](url)

**Comment by keshavk** [comment]
I am closing out this issue
